[project]
name = "lesion-tracking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Felipe Coutinho", email = "fcoelho.mrc@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
lesion-tracking = "lesion_tracking:main"

[build-system]
requires = ["uv_build>=0.9.25,<0.10.0"]
build-backend = "uv_build"
